"""baseline schema

Baselines the schema as it stood at the end of the prototype build. An existing
database created by the previous Base.metadata.create_all path is byte-identical
to what this revision produces and is adopted by stamping rather than upgrading
(see database.py: _adopt_or_upgrade).

Includes the evidence_chunks_fts FTS5 virtual table, which is not part of
Base.metadata and therefore invisible to autogenerate. It is declared here so
that a database built purely from migrations is complete.

Revision ID: 0001
Revises:
Create Date: 2026-08-14 17:07:42.935122
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=100), nullable=False),
    sa.Column('doc_title', sa.String(length=255), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('clause_ref', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_chunk_doc_id', ['doc_id'], unique=False)

    op.create_table('evidence_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('next_review', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.create_index('idx_evidence_doc_id', ['doc_id'], unique=False)
        batch_op.create_index('idx_evidence_status_created', ['status', 'created_at'], unique=False)

    op.create_table('questionnaire_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sandbox_id', sa.String(length=255), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_runs', schema=None) as batch_op:
        batch_op.create_index('idx_run_status', ['status'], unique=False)

    op.create_table('export_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('export_format', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questionnaire_files', schema=None) as batch_op:
        batch_op.create_index('idx_qfile_run_id', ['run_id'], unique=False)

    op.create_table('reviewer_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('question_ref', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('answer_col', sa.String(length=10), nullable=True),
    sa.Column('evidence_col', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_questions', schema=None) as batch_op:
        batch_op.create_index('idx_rquestion_run_id', ['run_id'], unique=False)

    op.create_table('sandbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_events', schema=None) as batch_op:
        batch_op.create_index('idx_sevent_run_id', ['run_id'], unique=False)

    op.create_table('gap_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('gap_reason', sa.Text(), nullable=False),
    sa.Column('closes_gap_with', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['run_questions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('citation_document', sa.String(length=100), nullable=True),
    sa.Column('citation_clause', sa.String(length=100), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('draft_answer', sa.Text(), nullable=True),
    sa.Column('reviewed_answer', sa.Text(), nullable=True),
    sa.Column('reviewer_edited', sa.Boolean(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('unsupported_reason', sa.Text(), nullable=True),
    sa.Column('closes_gap_with', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['run_questions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.create_index('idx_ranswer_question_id', ['question_id'], unique=False)
        batch_op.create_index('idx_ranswer_run_id', ['run_id'], unique=False)

    # ### end Alembic commands ###

    # FTS5 retrieval index. Not in Base.metadata, so autogenerate cannot see it.
    # Column list must stay in step with evidence_service.store_document_and_chunks.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS evidence_chunks_fts "
        "USING fts5(doc_id, doc_title, heading, clause_ref, content)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS evidence_chunks_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_ranswer_run_id')
        batch_op.drop_index('idx_ranswer_question_id')

    op.drop_table('run_answers')
    op.drop_table('gap_records')
    with op.batch_alter_table('sandbox_events', schema=None) as batch_op:
        batch_op.drop_index('idx_sevent_run_id')

    op.drop_table('sandbox_events')
    with op.batch_alter_table('run_questions', schema=None) as batch_op:
        batch_op.drop_index('idx_rquestion_run_id')

    op.drop_table('run_questions')
    op.drop_table('run_approvals')
    op.drop_table('reviewer_metrics')
    with op.batch_alter_table('questionnaire_files', schema=None) as batch_op:
        batch_op.drop_index('idx_qfile_run_id')

    op.drop_table('questionnaire_files')
    op.drop_table('job_statuses')
    op.drop_table('export_records')
    with op.batch_alter_table('questionnaire_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_run_status')

    op.drop_table('questionnaire_runs')
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.drop_index('idx_evidence_status_created')
        batch_op.drop_index('idx_evidence_doc_id')

    op.drop_table('evidence_documents')
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_chunk_doc_id')

    op.drop_table('evidence_chunks')
    # ### end Alembic commands ###
