"""verified citations and split confidence

Hand-written, not autogenerated (see CLAUDE.md rule 4).

Two changes:
  1. answer_citations — one row per citation, with a foreign key to the chunk the
     quote was actually found in and the result of verifying it.
  2. run_answers.confidence is split into answer_confidence and gap_confidence.
     The model reports its confidence that a gap IS a gap; that value shared a
     column with confidence in an answer, so 28 of 52 refused questions carried a
     non-zero number and one carried 1.0.

The split is done as: add both columns, backfill by evidence_status, then drop
the original. SQLite cannot drop a column in place, so batch_alter_table rebuilds
the table — which is also what applies the CHECK constraint.

Existing citation strings on run_answers are NOT migrated here. They are
backfilled by scripts/backfill_citations.py, which must run the real verifier
against the real chunks; a migration cannot do that.

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-14 17:41:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'answer_citations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('run_id', sa.String(length=36), nullable=False),
        sa.Column('answer_id', sa.String(length=36), nullable=False),
        sa.Column('chunk_id', sa.String(length=36), nullable=True),
        sa.Column('doc_id', sa.String(length=100), nullable=False),
        sa.Column('clause_ref', sa.String(length=100), nullable=True),
        sa.Column('quote', sa.Text(), nullable=True),
        sa.Column('quote_verified', sa.Boolean(), nullable=False),
        sa.Column('clause_verified', sa.Boolean(), nullable=False),
        sa.Column('resolution', sa.String(length=30), nullable=False),
        sa.Column('actual_clause_ref', sa.String(length=100), nullable=True),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['questionnaire_runs.id'], ),
        sa.ForeignKeyConstraint(['answer_id'], ['run_answers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('answer_citations', schema=None) as batch_op:
        batch_op.create_index('idx_acitation_answer_id', ['answer_id'], unique=False)
        batch_op.create_index('idx_acitation_run_id', ['run_id'], unique=False)

    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gap_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_note', sa.Text(), nullable=True))

    # Route the existing value to the column that matches its meaning.
    op.execute("""
        UPDATE run_answers
           SET gap_confidence = confidence, answer_confidence = NULL
         WHERE evidence_status = 'gap'
    """)
    op.execute("""
        UPDATE run_answers
           SET answer_confidence = confidence, gap_confidence = NULL
         WHERE evidence_status <> 'gap'
    """)

    # Rebuild without the ambiguous column, and make the invariant structural.
    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.create_check_constraint(
            'ck_run_answers_one_confidence',
            "(evidence_status = 'gap' AND answer_confidence IS NULL) OR "
            "(evidence_status <> 'gap' AND gap_confidence IS NULL)",
        )


def downgrade() -> None:
    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.drop_constraint('ck_run_answers_one_confidence', type_='check')
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=False, server_default='0.0'))

    op.execute("UPDATE run_answers SET confidence = COALESCE(answer_confidence, gap_confidence, 0.0)")

    with op.batch_alter_table('run_answers', schema=None) as batch_op:
        batch_op.drop_column('verification_note')
        batch_op.drop_column('gap_confidence')
        batch_op.drop_column('answer_confidence')

    with op.batch_alter_table('answer_citations', schema=None) as batch_op:
        batch_op.drop_index('idx_acitation_run_id')
        batch_op.drop_index('idx_acitation_answer_id')

    op.drop_table('answer_citations')
